config/routes.rb
Crs::Application.routes.draw do
	match 'clickers/' => "clickers#home"
	match 'clickers/auth' => "clickers#auth"
	match 'clickers/management' => "clickers#management"
	match 'clickers/reset_pwd' => "clickers#reset_pwd"
	match 'clickers/report' => "clickers#index"
	match 'clickers/test/:id' => "clickers#test"
	match 'clickers/score' => "clickers#score"
  resources :questions
	resources :clickers
	

end

app/models/clicker.rb
class Clicker < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
	validates :number, :presence => true
	validates :question, :presence => true
	validates :a, :presence => true
	validates :b, :presence => true
	validates :c, :presence => true
	validates :d, :presence => true
	validates :answer, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/clickers_controller.rb
class ClickersController < ApplicationController
  def home
    respond_to do |format|
      format.html # home.html.erb
    end
  end
  def auth
    respond_to do |format|
      format.html # auth.html.erb
    end
  end
  def management
    respond_to do |format|
      format.html # management.html.erb
    end
  end
  def reset_pwd
    respond_to do |format|
      format.html # reset_pwd.html.erb
    end
  end
	
  # GET /clickers
  # GET /clickers.xml
  def index
    	@clickers = Clicker.all			

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @clickers }
    end
  end

  def score
    respond_to do |format|
      format.html # score.html.erb
    end
  end

  def test
		@cur_number = params[:id]
		n = @cur_number.to_i
		if n > 1
		  n = n - 1
			q = Question.where(:number => n.to_s).first
			c = Clicker.where(:question_id => q.id.to_s).first
			if c == nil
				c = Clicker.new
				c.a_count = 0
				c.b_count = 0
				c.c_count = 0
				c.d_count = 0
				c.question_id = q.id
			end
#			p = params[:clicker][:response]
			p = params[:response]
			if p == 'A'
			  c.a_count = c.a_count + 1
			elsif p == 'B'
			  c.b_count += 1
			elsif p == 'C'
			  c.c_count += 1
			elsif p == 'D'
			  c.d_count += 1
			end
			c.save
		end
		if @cur_number.to_i > Question.last.number
			@cur_number = Question.last.number.to_s
		elsif @cur_number.to_i < Question.first.number
			@cur_number = Question.first.number.to_s
		end
    @question = Question.where(:number => @cur_number).first
		@clicker = Clicker.where(:question_id => @question.id.to_s).first
		if @clicker == nil
			@clicker = Clicker.new
		end
		@clicker.response = ""
		
    respond_to do |format|
      format.html # test.html.erb
    end
  end
	
end

app/controllers/clickers_controller_orig.rb
class ClickersController < ApplicationController
  # GET /clickers
  # GET /clickers.xml
  def index
    	@clickers = Clicker.all			

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @clickers }
    end
  end

  # GET /clickers/1
  # GET /clickers/1.xml
  def show
    @clicker = Clicker.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @clicker }
    end
  end

  # GET /clickers/new
  # GET /clickers/new.xml
  def new
		@clicker = Clicker.new			
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @clicker }
    end
  end

  # GET /clickers/1/edit
  def edit
    @clicker = Clicker.find(params[:id])
  end

  # POST /clickers
  # POST /clickers.xml
  def create
    @clicker = Clicker.new(params[:clicker])

    respond_to do |format|
      if @clicker.save
        format.html { redirect_to(@clicker, :notice => 'Clicker was successfully created.') }
        format.xml  { render :xml => @clicker, :status => :created, :location => @clicker }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @clicker.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /clickers/1
  # PUT /clickers/1.xml
  def update
    @clicker = Clicker.find(params[:id])

    respond_to do |format|
      if @clicker.update_attributes(params[:clicker])
        format.html { redirect_to(@clicker, :notice => 'Clicker was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @clicker.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /clickers/1
  # DELETE /clickers/1.xml
  def destroy
    @clicker = Clicker.find(params[:id])
    @clicker.destroy

    respond_to do |format|
      format.html { redirect_to(clickers_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # GET /questions
  # GET /questions.xml
  def index
    @questions = Question.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.xml
  def show
    @question = Question.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.xml
  def new
    @question = Question.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @question }
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
  end

  # POST /questions
  # POST /questions.xml
  def create
    @question = Question.new(params[:question])

    respond_to do |format|
      if @question.save
        format.html { redirect_to(@question, :notice => 'Question was successfully created.') }
        format.xml  { render :xml => @question, :status => :created, :location => @question }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @question.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.xml
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to(@question, :notice => 'Question was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @question.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.xml
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to(questions_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clickers_helper.rb
module ClickersHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/clickers/_form.html.erb
<%= form_for(@clicker) do |f| %>
  <% if @clicker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@clicker.errors.count, "error") %> prohibited this clicker from being saved:</h2>

      <ul>
      <% @clicker.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question_id %><br />
    <%= f.text_field :question_id %>
  </div>
  <div class="field">
    <%= f.label :a_count %><br />
    <%= f.text_field :a_count %>
  </div>
  <div class="field">
    <%= f.label :b_count %><br />
    <%= f.text_field :b_count %>
  </div>
  <div class="field">
    <%= f.label :c_count %><br />
    <%= f.text_field :c_count %>
  </div>
  <div class="field">
    <%= f.label :d_count %><br />
    <%= f.text_field :d_count %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clickers/auth.html.erb
<h1>Authentication</h1>

<p>Enter the Teacher's password:</p>

<input id="teacher_password" name="clicker[password]" size="30" type="text" />

<%= link_to 'Submit', '/clickers/auth' %> <br /> 

<%= link_to 'Home', '/clickers/' %>

<br /><br /><br />
Notes: Currently this function is not available.<br /> 
Temporarily, link to Management is added for testing purposes. <br /> 
<%= link_to 'Management', '/clickers/management' %> <br /> 

app/views/clickers/edit.html.erb
<h1>Editing clicker</h1>

<%= render 'form' %>

<%= link_to 'Show', @clicker %> |
<%= link_to 'Back', clickers_path %>

app/views/clickers/home.html.erb
<h1>Welcome to Classroom Response System!</h1>

<p>Please identify your role:</p>
<%= link_to 'Teacher', '/clickers/auth' %> <br />
<%= link_to 'Student', '/clickers/test/1' %>

app/views/clickers/index.html.erb
<h1>Listing clickers</h1>

<table>
  <tr>
    <th>Question</th>
    <th>A count</th>
    <th>B count</th>
    <th>C count</th>
    <th>D count</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clickers.each do |clicker| %>
  <tr>
    <td><%= clicker.question_id %></td>
    <td><%= clicker.a_count %></td>
    <td><%= clicker.b_count %></td>
    <td><%= clicker.c_count %></td>
    <td><%= clicker.d_count %></td>
    <td><%= link_to 'Edit', edit_clicker_path(clicker) %></td>
    <td><%= link_to 'Destroy', clicker, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Management', '/clickers/management' %>
<%= link_to 'Home', '/clickers/' %>

app/views/clickers/management.html.erb
<h1>Management Page</h1>


<%= link_to 'List Questions', questions_path %> <br />
<%= link_to 'Reset Password', '/clickers/reset_pwd' %> <br />
<%= link_to 'View Report', '/clickers/report' %>
<%= link_to 'Home', '/clickers/' %>

app/views/clickers/new.html.erb
<h1>New clicker</h1>

<%= render 'form' %>

<%= link_to 'Back', clickers_path %>

app/views/clickers/reset_pwd.html.erb
<h1>Password Setting</h1>

<p>Enter the current password:</p>
<input id="current_password" name="clicker[cur_password]" size="30" type="text" /><br />

<p>Enter a new password:</p>
<input id="new_password" name="clicker[new_password]" size="30" type="text" /><br />

<p>Re-enter the new password:</p>
<input id="confirm_password" name="clicker[confirm_password]" size="30" type="text" /><br />
<br />

<%= link_to 'Management', '/clickers/management' %>
<%= link_to 'Home', '/clickers/' %>

app/views/clickers/score.html.erb
<h1>Test Score</h1>


<%= link_to 'Home', '/clickers/' %>

app/views/clickers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Question:</b>
  <%= @clicker.question_id %>
</p>

<p>
  <b>A count:</b>
  <%= @clicker.a_count %>
</p>

<p>
  <b>B count:</b>
  <%= @clicker.b_count %>
</p>

<p>
  <b>C count:</b>
  <%= @clicker.c_count %>
</p>

<p>
  <b>D count:</b>
  <%= @clicker.d_count %>
</p>


<%= link_to 'Edit', edit_clicker_path(@clicker) %> |
<%= link_to 'Back', clickers_path %>

app/views/clickers/test.html.erb
<%= form_for(@clicker) do |f| %>
  <% if @clicker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@clicker.errors.count, "error") %> prohibited this clicker from being saved:</h2>

      <ul>
      <% @clicker.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<h1>Test</h1>

<table>
  <tr>
    <th>Number</th>
    <th>Question</th>
    <th>A</th>
    <th>B</th>
    <th>C</th>
    <th>D</th>
  </tr>

  <tr>
    <td><%= @question.number %></td>
    <td><%= @question.question %></td>		
    <td><%= @question.a %></td>
    <td><%= @question.b %></td>		
    <td><%= @question.c %></td>		
    <td><%= @question.d %></td>
  </tr>
  <tr>
		<td></td><td></td><td><%= f.radio_button :response, 'A' %></td>
		<td><%= f.radio_button :response, 'B' %></td>
		<td><%= f.radio_button :response, 'C' %></td>
		<td><%= f.radio_button :response, 'D' %></td>
  </tr>
	<tr>
		<td><%= f.submit %>
  </tr>
</table>

<br />
<% next_number = @question.number + 1
	 if next_number > Question.count
   		path = '/clickers/score'	 	
	 else
   		path = '/clickers/test/'+next_number.to_s
	 end
%>
<br />

<%= link_to 'Next', path %>

<%= link_to 'Home', '/clickers/' %>


<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crs</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br />
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label :question %><br />
    <%= f.text_area :question %>
  </div>
  <div class="field">
    <%= f.label :a %><br />
    <%= f.text_field :a %>
  </div>
  <div class="field">
    <%= f.label :b %><br />
    <%= f.text_field :b %>
  </div>
  <div class="field">
    <%= f.label :c %><br />
    <%= f.text_field :c %>
  </div>
  <div class="field">
    <%= f.label :d %><br />
    <%= f.text_field :d %>
  </div>
  <div class="field">
    <%= f.label :answer %><br />
    <%= f.text_field :answer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>Listing questions</h1>

<table>
  <tr>
    <th>Number</th>
    <th>Question</th>
    <th>A</th>
    <th>B</th>
    <th>C</th>
    <th>D</th>
    <th>Answer</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @questions.each do |question| %>
  <tr>
    <td><%= question.number %></td>
    <td><%= question.question %></td>
    <td><%= question.a %></td>
    <td><%= question.b %></td>
    <td><%= question.c %></td>
    <td><%= question.d %></td>
    <td><%= question.answer %></td>
    <td><%= link_to 'Show', question %></td>
    <td><%= link_to 'Edit', edit_question_path(question) %></td>
    <td><%= link_to 'Destroy', question, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Question', new_question_path %>
<%= link_to 'Management', '/clickers/management' %>
<%= link_to 'Home', '/clickers/' %>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Number:</b>
  <%= @question.number %>
</p>

<p>
  <b>Question:</b>
  <%= @question.question %>
</p>

<p>
  <b>A:</b>
  <%= @question.a %>
</p>

<p>
  <b>B:</b>
  <%= @question.b %>
</p>

<p>
  <b>C:</b>
  <%= @question.c %>
</p>

<p>
  <b>D:</b>
  <%= @question.d %>
</p>

<p>
  <b>Answer:</b>
  <%= @question.answer %>
</p>


<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>